// Mocks generated by Mockito 5.4.6 from annotations
// in userverse_dart_client/test/services/user_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:userverse_dart_client/src/utils/base_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BaseApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApiService extends _i1.Mock implements _i2.BaseApiService {
  MockBaseApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setBearerToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setBearerToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearBearerToken() => super.noSuchMethod(
        Invocation.method(
          #clearBearerToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
    Map<String, String>? additionalHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #queryParams: queryParams,
            #additionalHeaders: additionalHeaders,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> post(
    String? endpoint, {
    dynamic body,
    Map<String, String>? additionalHeaders,
    String? basicAuthUsername,
    String? basicAuthPassword,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #body: body,
            #additionalHeaders: additionalHeaders,
            #basicAuthUsername: basicAuthUsername,
            #basicAuthPassword: basicAuthPassword,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> patch(
    String? endpoint, {
    dynamic body,
    Map<String, String>? additionalHeaders,
    String? basicAuthUsername,
    String? basicAuthPassword,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {
            #body: body,
            #additionalHeaders: additionalHeaders,
            #basicAuthUsername: basicAuthUsername,
            #basicAuthPassword: basicAuthPassword,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> put(
    String? endpoint, {
    dynamic body,
    Map<String, String>? additionalHeaders,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #body: body,
            #additionalHeaders: additionalHeaders,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    dynamic body,
    Map<String, String>? additionalHeaders,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #body: body,
            #additionalHeaders: additionalHeaders,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
